version: '2'
services:
  cogserviceintegration-app:
    image: cogserviceintegration
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
      - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cogserviceintegration-cassandra
      - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
      - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK -Djava.net.preferIPv4Stack=true
  cogserviceintegration-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: cogserviceintegration-cassandra
  cogserviceintegration-cassandra-node:
    image: cassandra:3.11.4
    environment:
      - CASSANDRA_SEEDS=cogserviceintegration-cassandra
  cogserviceintegration-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: cogserviceintegration-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
  jhipster-registry:
    extends:
      file: jhipster-registry.yml
      service: jhipster-registry
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
      - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
